<a href="https://colab.research.google.com/github/Pankaj-70/dl_practicals/blob/main/keras_hyperparameter_tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv('/content/sample_data/diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
df.shape

(768, 9)

In [6]:
X=df.iloc[:, :-1].values
y=df.iloc[:,-1].values

In [7]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=2)

In [8]:
st=StandardScaler()
X_train=st.fit_transform(X_train)
X_test=st.transform(X_test)

In [39]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Input, Dropout

In [10]:
model=Sequential([
    Input(shape=(8,)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [11]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [12]:
model.fit(X_train, y_train, batch_size=32, validation_data=(X_test, y_test), epochs=100)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 72ms/step - accuracy: 0.5407 - loss: 0.7027 - val_accuracy: 0.5455 - val_loss: 0.6892
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6466 - loss: 0.6442 - val_accuracy: 0.6558 - val_loss: 0.6380
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.6029 - val_accuracy: 0.7143 - val_loss: 0.6008
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5729 - val_accuracy: 0.7143 - val_loss: 0.5748
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5516 - val_accuracy: 0.7338 - val_loss: 0.5528
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.5335 - val_accuracy: 0.7273 - val_loss: 0.5356
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.5191 - val_accuracy: 0.7273 - val_loss: 0.5229
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.5082 - val_accuracy: 0.7403 - val_loss: 0.5137
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4987 - val_accuracy: 0.7468 - val_loss: 0.5050
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4907 - val_accuracy: 0.7468 - val_loss: 0.4993
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4836 - val_accuracy: 0.7532 - val_loss: 0.4940
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4782 - val_accuracy: 0.7532 - val_loss: 0.4878
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4734 - val_accuracy: 0.7597 - val_loss: 0.4835
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4692 - val_accuracy: 0.7468 - val_loss: 0.4811
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4667 - val_accuracy: 0.7468 - val_loss: 0.4784
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4638 - val_accuracy: 0.7532 - val_loss: 0.4784
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4613 - val_accuracy: 0.7532 - val_loss: 0.4758
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4596 - val_accuracy: 0.7532 - val_loss: 0.4740
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4573 - val_accuracy: 0.7597 - val_loss: 0.4733
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4556 - val_accuracy: 0.7662 - val_loss: 0.4718
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4538 - val_accuracy: 0.7662 - val_loss: 0.4694
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4523 - val_accuracy: 0.7662 - val_loss: 0.4693
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4514 - val_accuracy: 0.7662 - val_loss: 0.4686
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4502 - val_accuracy: 0.7662 - val_loss: 0.4681
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4489 - val_accuracy: 0.7662 - val_loss: 0.4670
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4482 - val_accuracy: 0.7662 - val_loss: 0.4677
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4468 - val_accuracy: 0.7662 - val_loss: 0.4681
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4462 - val_accuracy: 0.7662 - val_loss: 0.4661
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4452 - val_accuracy: 0.7597 - val_loss: 0.4654
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4442 - val_accuracy: 0.7468 - val_loss: 0.4682
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4433 - val_accuracy: 0.7468 - val_loss: 0.4668
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4428 - val_accuracy: 0.7468 - val_loss: 0.4653
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4420 - val_accuracy: 0.7468 - val_loss: 0.4662
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4410 - val_accuracy: 0.7468 - val_loss: 0.4650
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7964 - loss: 0.4411 - val_accuracy: 0.7532 - val_loss: 0.4644
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4397 - val_accuracy: 0.7468 - val_loss: 0.4650
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7964 - loss: 0.4394 - val_accuracy: 0.7532 - val_loss: 0.4644
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4391 - val_accuracy: 0.7532 - val_loss: 0.4644
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4382 - val_accuracy: 0.7532 - val_loss: 0.4659
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4375 - val_accuracy: 0.7597 - val_loss: 0.4664
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8013 - loss: 0.4374 - val_accuracy: 0.7597 - val_loss: 0.4667
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4370 - val_accuracy: 0.7597 - val_loss: 0.4650
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4359 - val_accuracy: 0.7597 - val_loss: 0.4654
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4356 - val_accuracy: 0.7597 - val_loss: 0.4645
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4355 - val_accuracy: 0.7597 - val_loss: 0.4658
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4352 - val_accuracy: 0.7597 - val_loss: 0.4650
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4341 - val_accuracy: 0.7597 - val_loss: 0.4661
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4335 - val_accuracy: 0.7597 - val_loss: 0.4657
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4332 - val_accuracy: 0.7597 - val_loss: 0.4661
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4326 - val_accuracy: 0.7597 - val_loss: 0.4652
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4325 - val_accuracy: 0.7597 - val_loss: 0.4628
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4321 - val_accuracy: 0.7532 - val_loss: 0.4638
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4311 - val_accuracy: 0.7532 - val_loss: 0.4653
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4309 - val_accuracy: 0.7597 - val_loss: 0.4667
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4307 - val_accuracy: 0.7597 - val_loss: 0.4645
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4300 - val_accuracy: 0.7662 - val_loss: 0.4643
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4293 - val_accuracy: 0.7662 - val_loss: 0.4639
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4292 - val_accuracy: 0.7597 - val_loss: 0.4646
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4289 - val_accuracy: 0.7597 - val_loss: 0.4641
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4286 - val_accuracy: 0.7662 - val_loss: 0.4655
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8062 - loss: 0.4282 - val_accuracy: 0.7597 - val_loss: 0.4640
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4279 - val_accuracy: 0.7597 - val_loss: 0.4661
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4275 - val_accuracy: 0.7597 - val_loss: 0.4653
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4272 - val_accuracy: 0.7727 - val_loss: 0.4655
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4260 - val_accuracy: 0.7662 - val_loss: 0.4630
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4261 - val_accuracy: 0.7727 - val_loss: 0.4613
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4257 - val_accuracy: 0.7662 - val_loss: 0.4635
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4249 - val_accuracy: 0.7662 - val_loss: 0.4641
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4250 - val_accuracy: 0.7662 - val_loss: 0.4628
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4262 - val_accuracy: 0.7727 - val_loss: 0.4637
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4239 - val_accuracy: 0.7727 - val_loss: 0.4657
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4236 - val_accuracy: 0.7727 - val_loss: 0.4650
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4234 - val_accuracy: 0.7727 - val_loss: 0.4654
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4226 - val_accuracy: 0.7727 - val_loss: 0.4648
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4225 - val_accuracy: 0.7727 - val_loss: 0.4657
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4226 - val_accuracy: 0.7727 - val_loss: 0.4653
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4218 - val_accuracy: 0.7727 - val_loss: 0.4647
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4214 - val_accuracy: 0.7727 - val_loss: 0.4635
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4209 - val_accuracy: 0.7662 - val_loss: 0.4648
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4208 - val_accuracy: 0.7662 - val_loss: 0.4628
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4203 - val_accuracy: 0.7662 - val_loss: 0.4642
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4205 - val_accuracy: 0.7662 - val_loss: 0.4655
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4205 - val_accuracy: 0.7662 - val_loss: 0.4616
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4195 - val_accuracy: 0.7662 - val_loss: 0.4642
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4188 - val_accuracy: 0.7662 - val_loss: 0.4647
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4184 - val_accuracy: 0.7597 - val_loss: 0.4669
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4186 - val_accuracy: 0.7662 - val_loss: 0.4676
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4181 - val_accuracy: 0.7662 - val_loss: 0.4646
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4175 - val_accuracy: 0.7792 - val_loss: 0.4647
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4170 - val_accuracy: 0.7792 - val_loss: 0.4633
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4174 - val_accuracy: 0.7792 - val_loss: 0.4651
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8127 - loss: 0.4173 - val_accuracy: 0.7727 - val_loss: 0.4668
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8111 - loss: 0.4163 - val_accuracy: 0.7727 - val_loss: 0.4658
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8078 - loss: 0.4164 - val_accuracy: 0.7792 - val_loss: 0.4674
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8094 - loss: 0.4158 - val_accuracy: 0.7727 - val_loss: 0.4668
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.4155 - val_accuracy: 0.7792 - val_loss: 0.4670
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8094 - loss: 0.4154 - val_accuracy: 0.7792 - val_loss: 0.4689
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8111 - loss: 0.4152 - val_accuracy: 0.7792 - val_loss: 0.4680
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8094 - loss: 0.4149 - val_accuracy: 0.7662 - val_loss: 0.4723
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8111 - loss: 0.4151 - val_accuracy: 0.7727 - val_loss: 0.4685

In [13]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 6.3 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [14]:
import kerastuner as kt

/tmp/ipykernel_4564/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [15]:
def build_model(hp):
  model = Sequential([
      Input(shape=(8, )),
      Dense(32, activation='relu'),
      Dense(1, activation='sigmoid')
  ])

  optimizer=hp.Choice('optimizer', values = ['sgd', 'adam', 'rmsrop', 'adadelta'])

  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

  model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

  return model

In [16]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5)

Epoch 1/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 104ms/step - accuracy: 0.6612 - loss: 0.6523 - val_accuracy: 0.7013 - val_loss: 0.6262
Epoch 2/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6938 - loss: 0.6327 - val_accuracy: 0.7013 - val_loss: 0.6092
Epoch 3/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7052 - loss: 0.6180 - val_accuracy: 0.7143 - val_loss: 0.5947
Epoch 4/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7101 - loss: 0.6050 - val_accuracy: 0.7338 - val_loss: 0.5804
Epoch 5/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7150 - loss: 0.5928 - val_accuracy: 0.7338 - val_loss: 0.5684
Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7248 - loss: 0.5819 - val_accuracy: 0.7273 - val_loss: 0.5580
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7362 - loss: 0.5732 - val_accuracy: 0.7338 - val_loss: 0.5494
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7362 - loss: 0.5649 - val_accuracy: 0.7338 - val_loss: 0.5419
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7345 - loss: 0.5579 - val_accuracy: 0.7338 - val_loss: 0.5358
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7362 - loss: 0.5514 - val_accuracy: 0.7338 - val_loss: 0.5307

In [17]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test), verbose=1)

Trial 4 Complete [00h 00m 06s]
val_accuracy: 0.6688311696052551

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 27s

In [18]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'sgd'}

In [19]:
model=tuner.get_best_models(num_models=1)[0]

Epoch 1/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.5765 - loss: 0.6784 - val_accuracy: 0.5974 - val_loss: 0.6679
Epoch 2/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6156 - loss: 0.6539 - val_accuracy: 0.6623 - val_loss: 0.6443
Epoch 3/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6337 - val_accuracy: 0.6753 - val_loss: 0.6245
Epoch 4/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6710 - loss: 0.6160 - val_accuracy: 0.6753 - val_loss: 0.6097
Epoch 5/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.6019 - val_accuracy: 0.6883 - val_loss: 0.5965
Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.5892 - val_accuracy: 0.6818 - val_loss: 0.5841
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.5778 - val_accuracy: 0.6883 - val_loss: 0.5742
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5675 - val_accuracy: 0.6818 - val_loss: 0.5653
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5586 - val_accuracy: 0.6883 - val_loss: 0.5580
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5509 - val_accuracy: 0.6948 - val_loss: 0.5519

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 323 (1.27 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [21]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.5349 - val_accuracy: 0.7792 - val_loss: 0.4919
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5292 - val_accuracy: 0.7727 - val_loss: 0.4879
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.5236 - val_accuracy: 0.7727 - val_loss: 0.4841
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.5187 - val_accuracy: 0.7857 - val_loss: 0.4803
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.5145 - val_accuracy: 0.7727 - val_loss: 0.4778
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.5102 - val_accuracy: 0.7792 - val_loss: 0.4749
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.5067 - val_accuracy: 0.7727 - val_loss: 0.4727
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.5030 - val_accuracy: 0.7857 - val_loss: 0.4709
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.5000 - val_accuracy: 0.7857 - val_loss: 0.4686
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4971 - val_accuracy: 0.7857 - val_loss: 0.4676
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4943 - val_accuracy: 0.7857 - val_loss: 0.4657
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4919 - val_accuracy: 0.7922 - val_loss: 0.4642
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4893 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4871 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4851 - val_accuracy: 0.7987 - val_loss: 0.4615
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4831 - val_accuracy: 0.7857 - val_loss: 0.4607
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4814 - val_accuracy: 0.7727 - val_loss: 0.4596
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4797 - val_accuracy: 0.7792 - val_loss: 0.4584
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4780 - val_accuracy: 0.7727 - val_loss: 0.4579
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4765 - val_accuracy: 0.7792 - val_loss: 0.4570
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4752 - val_accuracy: 0.7792 - val_loss: 0.4567
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4740 - val_accuracy: 0.7792 - val_loss: 0.4562
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4728 - val_accuracy: 0.7792 - val_loss: 0.4558
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4717 - val_accuracy: 0.7727 - val_loss: 0.4559
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4705 - val_accuracy: 0.7727 - val_loss: 0.4556
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4695 - val_accuracy: 0.7727 - val_loss: 0.4550
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4684 - val_accuracy: 0.7792 - val_loss: 0.4542
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4673 - val_accuracy: 0.7792 - val_loss: 0.4543
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4663 - val_accuracy: 0.7727 - val_loss: 0.4540
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4656 - val_accuracy: 0.7727 - val_loss: 0.4533
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4647 - val_accuracy: 0.7727 - val_loss: 0.4532
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4639 - val_accuracy: 0.7792 - val_loss: 0.4528
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4632 - val_accuracy: 0.7727 - val_loss: 0.4525
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4623 - val_accuracy: 0.7792 - val_loss: 0.4524
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4615 - val_accuracy: 0.7792 - val_loss: 0.4525
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4609 - val_accuracy: 0.7792 - val_loss: 0.4523
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4602 - val_accuracy: 0.7727 - val_loss: 0.4527
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4596 - val_accuracy: 0.7727 - val_loss: 0.4525
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4590 - val_accuracy: 0.7727 - val_loss: 0.4527
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4584 - val_accuracy: 0.7727 - val_loss: 0.4537
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4580 - val_accuracy: 0.7727 - val_loss: 0.4542
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4575 - val_accuracy: 0.7727 - val_loss: 0.4541
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4569 - val_accuracy: 0.7727 - val_loss: 0.4535
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4563 - val_accuracy: 0.7727 - val_loss: 0.4524
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4558 - val_accuracy: 0.7727 - val_loss: 0.4522
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4554 - val_accuracy: 0.7792 - val_loss: 0.4519
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4549 - val_accuracy: 0.7792 - val_loss: 0.4518
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4546 - val_accuracy: 0.7727 - val_loss: 0.4523
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4542 - val_accuracy: 0.7727 - val_loss: 0.4523
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4537 - val_accuracy: 0.7727 - val_loss: 0.4526
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4534 - val_accuracy: 0.7727 - val_loss: 0.4526
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4531 - val_accuracy: 0.7727 - val_loss: 0.4530
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4527 - val_accuracy: 0.7727 - val_loss: 0.4533
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4524 - val_accuracy: 0.7727 - val_loss: 0.4525
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4521 - val_accuracy: 0.7727 - val_loss: 0.4525
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4517 - val_accuracy: 0.7792 - val_loss: 0.4520
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4514 - val_accuracy: 0.7792 - val_loss: 0.4520
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4511 - val_accuracy: 0.7792 - val_loss: 0.4512
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4509 - val_accuracy: 0.7792 - val_loss: 0.4510
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4505 - val_accuracy: 0.7792 - val_loss: 0.4513
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4505 - val_accuracy: 0.7792 - val_loss: 0.4515
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4501 - val_accuracy: 0.7792 - val_loss: 0.4517
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4498 - val_accuracy: 0.7792 - val_loss: 0.4520
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4493 - val_accuracy: 0.7792 - val_loss: 0.4520
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4492 - val_accuracy: 0.7792 - val_loss: 0.4521
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4490 - val_accuracy: 0.7792 - val_loss: 0.4521
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4487 - val_accuracy: 0.7792 - val_loss: 0.4522
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4484 - val_accuracy: 0.7792 - val_loss: 0.4522
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4482 - val_accuracy: 0.7857 - val_loss: 0.4518
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4481 - val_accuracy: 0.7857 - val_loss: 0.4526
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4478 - val_accuracy: 0.7857 - val_loss: 0.4525
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4477 - val_accuracy: 0.7857 - val_loss: 0.4522
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4474 - val_accuracy: 0.7792 - val_loss: 0.4526
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4472 - val_accuracy: 0.7792 - val_loss: 0.4525
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4471 - val_accuracy: 0.7792 - val_loss: 0.4529
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4468 - val_accuracy: 0.7857 - val_loss: 0.4523
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4465 - val_accuracy: 0.7792 - val_loss: 0.4529
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4463 - val_accuracy: 0.7792 - val_loss: 0.4532
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4462 - val_accuracy: 0.7857 - val_loss: 0.4538
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4460 - val_accuracy: 0.7857 - val_loss: 0.4538
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4459 - val_accuracy: 0.7857 - val_loss: 0.4533
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4456 - val_accuracy: 0.7857 - val_loss: 0.4532
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4455 - val_accuracy: 0.7857 - val_loss: 0.4532
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4452 - val_accuracy: 0.7857 - val_loss: 0.4535
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4451 - val_accuracy: 0.7857 - val_loss: 0.4532
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4449 - val_accuracy: 0.7857 - val_loss: 0.4533
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4447 - val_accuracy: 0.7857 - val_loss: 0.4533
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4446 - val_accuracy: 0.7857 - val_loss: 0.4532
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4444 - val_accuracy: 0.7857 - val_loss: 0.4532
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4442 - val_accuracy: 0.7857 - val_loss: 0.4535
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4440 - val_accuracy: 0.7857 - val_loss: 0.4539
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4440 - val_accuracy: 0.7857 - val_loss: 0.4539
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4437 - val_accuracy: 0.7922 - val_loss: 0.4540
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4436 - val_accuracy: 0.7857 - val_loss: 0.4542

In [22]:
def build_model(hp):

  units=hp.Int('units', min_value=8, max_value=128, step=8)
  model=Sequential([
      Input(shape=(8, )),
      Dense(units=units, activation='relu'),
      Dense(1, activation='sigmoid')
  ])
  model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [23]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5,
                      directory='models',
                      project_name='dl')

In [24]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 05s]
val_accuracy: 0.7402597665786743

Best val_accuracy So Far: 0.7727272510528564
Total elapsed time: 00h 00m 20s

In [25]:
tuner.get_best_hyperparameters()[0].values

{'units': 80}

In [26]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [27]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 80)             │           720 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            81 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 801 (3.13 KB)

 Trainable params: 801 (3.13 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.7573 - loss: 0.5315 - val_accuracy: 0.7597 - val_loss: 0.5106
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.5028 - val_accuracy: 0.7662 - val_loss: 0.4861
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4858 - val_accuracy: 0.7792 - val_loss: 0.4718
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4740 - val_accuracy: 0.7857 - val_loss: 0.4656
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4662 - val_accuracy: 0.7792 - val_loss: 0.4617
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4617 - val_accuracy: 0.7792 - val_loss: 0.4580
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4566 - val_accuracy: 0.7792 - val_loss: 0.4561
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4540 - val_accuracy: 0.7727 - val_loss: 0.4553
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4507 - val_accuracy: 0.7857 - val_loss: 0.4572
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4486 - val_accuracy: 0.7857 - val_loss: 0.4554
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4460 - val_accuracy: 0.7857 - val_loss: 0.4538
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4450 - val_accuracy: 0.7857 - val_loss: 0.4556
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4434 - val_accuracy: 0.7857 - val_loss: 0.4539
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4422 - val_accuracy: 0.7792 - val_loss: 0.4547
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4408 - val_accuracy: 0.7792 - val_loss: 0.4548
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4391 - val_accuracy: 0.7792 - val_loss: 0.4581
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4378 - val_accuracy: 0.7792 - val_loss: 0.4595
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4375 - val_accuracy: 0.7792 - val_loss: 0.4612
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4359 - val_accuracy: 0.7857 - val_loss: 0.4566
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4348 - val_accuracy: 0.7792 - val_loss: 0.4574
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4335 - val_accuracy: 0.7857 - val_loss: 0.4579
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4327 - val_accuracy: 0.7857 - val_loss: 0.4584
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4320 - val_accuracy: 0.7857 - val_loss: 0.4582
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4308 - val_accuracy: 0.7857 - val_loss: 0.4580
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4302 - val_accuracy: 0.7857 - val_loss: 0.4569
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4291 - val_accuracy: 0.7857 - val_loss: 0.4580
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4285 - val_accuracy: 0.7792 - val_loss: 0.4592
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4280 - val_accuracy: 0.7792 - val_loss: 0.4608
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4273 - val_accuracy: 0.7792 - val_loss: 0.4595
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4267 - val_accuracy: 0.7792 - val_loss: 0.4590
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4256 - val_accuracy: 0.7727 - val_loss: 0.4599
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4256 - val_accuracy: 0.7857 - val_loss: 0.4572
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4243 - val_accuracy: 0.7987 - val_loss: 0.4621
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4237 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4228 - val_accuracy: 0.7922 - val_loss: 0.4607
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4220 - val_accuracy: 0.7922 - val_loss: 0.4639
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4210 - val_accuracy: 0.7857 - val_loss: 0.4640
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4205 - val_accuracy: 0.7857 - val_loss: 0.4619
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4202 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4189 - val_accuracy: 0.7857 - val_loss: 0.4555
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4189 - val_accuracy: 0.7987 - val_loss: 0.4585
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4180 - val_accuracy: 0.7987 - val_loss: 0.4638
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4173 - val_accuracy: 0.7922 - val_loss: 0.4628
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4189 - val_accuracy: 0.7922 - val_loss: 0.4596
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4153 - val_accuracy: 0.7922 - val_loss: 0.4621
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4150 - val_accuracy: 0.7922 - val_loss: 0.4659
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4154 - val_accuracy: 0.7922 - val_loss: 0.4678
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8046 - loss: 0.4141 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8062 - loss: 0.4135 - val_accuracy: 0.7922 - val_loss: 0.4619
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4126 - val_accuracy: 0.7857 - val_loss: 0.4637
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4129 - val_accuracy: 0.7922 - val_loss: 0.4630
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8094 - loss: 0.4119 - val_accuracy: 0.7922 - val_loss: 0.4619
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.4114 - val_accuracy: 0.7922 - val_loss: 0.4647
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4100 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4094 - val_accuracy: 0.7987 - val_loss: 0.4673
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7997 - loss: 0.4098 - val_accuracy: 0.7922 - val_loss: 0.4694
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4084 - val_accuracy: 0.7987 - val_loss: 0.4671
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4085 - val_accuracy: 0.7987 - val_loss: 0.4673
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4093 - val_accuracy: 0.7922 - val_loss: 0.4618
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4069 - val_accuracy: 0.7987 - val_loss: 0.4694
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4074 - val_accuracy: 0.7987 - val_loss: 0.4661
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8046 - loss: 0.4052 - val_accuracy: 0.7987 - val_loss: 0.4684
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4060 - val_accuracy: 0.7922 - val_loss: 0.4655
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4041 - val_accuracy: 0.7987 - val_loss: 0.4714
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4043 - val_accuracy: 0.7987 - val_loss: 0.4708
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.8029 - loss: 0.4036 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4032 - val_accuracy: 0.7987 - val_loss: 0.4684
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4024 - val_accuracy: 0.7987 - val_loss: 0.4682
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4031 - val_accuracy: 0.7987 - val_loss: 0.4687
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.8062 - loss: 0.4016 - val_accuracy: 0.7987 - val_loss: 0.4691
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4013 - val_accuracy: 0.7987 - val_loss: 0.4705
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4001 - val_accuracy: 0.7987 - val_loss: 0.4682
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3996 - val_accuracy: 0.7987 - val_loss: 0.4692
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3985 - val_accuracy: 0.7987 - val_loss: 0.4673
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3991 - val_accuracy: 0.7987 - val_loss: 0.4664
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3992 - val_accuracy: 0.7987 - val_loss: 0.4687
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3979 - val_accuracy: 0.7987 - val_loss: 0.4657
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3976 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3964 - val_accuracy: 0.7987 - val_loss: 0.4638
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3966 - val_accuracy: 0.7987 - val_loss: 0.4690
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3956 - val_accuracy: 0.7987 - val_loss: 0.4660
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3953 - val_accuracy: 0.7987 - val_loss: 0.4656
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3948 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3960 - val_accuracy: 0.7987 - val_loss: 0.4701
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3943 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3933 - val_accuracy: 0.8052 - val_loss: 0.4674
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3929 - val_accuracy: 0.8052 - val_loss: 0.4679
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3921 - val_accuracy: 0.7987 - val_loss: 0.4693
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3923 - val_accuracy: 0.7987 - val_loss: 0.4693
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3929 - val_accuracy: 0.7987 - val_loss: 0.4705
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3910 - val_accuracy: 0.7987 - val_loss: 0.4713
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3912 - val_accuracy: 0.8052 - val_loss: 0.4682
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3901 - val_accuracy: 0.7987 - val_loss: 0.4669
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3895 - val_accuracy: 0.8052 - val_loss: 0.4699

In [29]:
def build_model(hp):
  model=Sequential()

  model.add(Input(shape=(8, )))

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model.add(Dense(72, activation='relu'))

  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [33]:
tuner=kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory='models',
    project_name='num_layers'
)

In [34]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 06s]
val_accuracy: 0.7727272510528564

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 39s

In [35]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4}

In [36]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [37]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 72)             │           648 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 72)             │         5,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 72)             │         5,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 72)             │         5,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            73 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 16,489 (64.41 KB)

 Trainable params: 16,489 (64.41 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 6s 120ms/step - accuracy: 0.7785 - loss: 0.4614 - val_accuracy: 0.7792 - val_loss: 0.4724
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7997 - loss: 0.4380 - val_accuracy: 0.7987 - val_loss: 0.4769
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7997 - loss: 0.4317 - val_accuracy: 0.7857 - val_loss: 0.4759
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4313 - val_accuracy: 0.8117 - val_loss: 0.4746
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8078 - loss: 0.4129 - val_accuracy: 0.7792 - val_loss: 0.4738
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8127 - loss: 0.4078 - val_accuracy: 0.7987 - val_loss: 0.4710
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.3988 - val_accuracy: 0.7922 - val_loss: 0.4825
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8192 - loss: 0.3846 - val_accuracy: 0.7987 - val_loss: 0.4877
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.3834 - val_accuracy: 0.7922 - val_loss: 0.4817
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8355 - loss: 0.3677 - val_accuracy: 0.7792 - val_loss: 0.5008
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8339 - loss: 0.3616 - val_accuracy: 0.7857 - val_loss: 0.4969
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8420 - loss: 0.3452 - val_accuracy: 0.7857 - val_loss: 0.5006
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8485 - loss: 0.3308 - val_accuracy: 0.7792 - val_loss: 0.5254
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8420 - loss: 0.3308 - val_accuracy: 0.7662 - val_loss: 0.5266
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8616 - loss: 0.3178 - val_accuracy: 0.7727 - val_loss: 0.5449
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8762 - loss: 0.2969 - val_accuracy: 0.7597 - val_loss: 0.5801
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8681 - loss: 0.2954 - val_accuracy: 0.7468 - val_loss: 0.6018
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8583 - loss: 0.3080 - val_accuracy: 0.7792 - val_loss: 0.5749
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8893 - loss: 0.2717 - val_accuracy: 0.7468 - val_loss: 0.5935
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8958 - loss: 0.2549 - val_accuracy: 0.7273 - val_loss: 0.6176
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9088 - loss: 0.2468 - val_accuracy: 0.7338 - val_loss: 0.6807
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9218 - loss: 0.2180 - val_accuracy: 0.7597 - val_loss: 0.6786
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9169 - loss: 0.2107 - val_accuracy: 0.7468 - val_loss: 0.7159
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9218 - loss: 0.2021 - val_accuracy: 0.7403 - val_loss: 0.7321
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9316 - loss: 0.1862 - val_accuracy: 0.7468 - val_loss: 0.7580
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9202 - loss: 0.2123 - val_accuracy: 0.7338 - val_loss: 0.7751
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9283 - loss: 0.1769 - val_accuracy: 0.7338 - val_loss: 0.7964
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9430 - loss: 0.1654 - val_accuracy: 0.7208 - val_loss: 0.8807
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9365 - loss: 0.1689 - val_accuracy: 0.7013 - val_loss: 0.8817
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9446 - loss: 0.1519 - val_accuracy: 0.7078 - val_loss: 0.9476
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9577 - loss: 0.1278 - val_accuracy: 0.7273 - val_loss: 1.0476
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9609 - loss: 0.1292 - val_accuracy: 0.7208 - val_loss: 0.9906
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9658 - loss: 0.1133 - val_accuracy: 0.7013 - val_loss: 1.0438
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9642 - loss: 0.1211 - val_accuracy: 0.7403 - val_loss: 1.0920
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9544 - loss: 0.1185 - val_accuracy: 0.7078 - val_loss: 1.1109
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.9479 - loss: 0.1368 - val_accuracy: 0.7273 - val_loss: 1.0476
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.9560 - loss: 0.1087 - val_accuracy: 0.6948 - val_loss: 1.2104
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9723 - loss: 0.0957 - val_accuracy: 0.7338 - val_loss: 1.1900
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9837 - loss: 0.0748 - val_accuracy: 0.7078 - val_loss: 1.2103
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9788 - loss: 0.0728 - val_accuracy: 0.7143 - val_loss: 1.2956
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9772 - loss: 0.0735 - val_accuracy: 0.7078 - val_loss: 1.2316
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9853 - loss: 0.0543 - val_accuracy: 0.7078 - val_loss: 1.3914
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9837 - loss: 0.0589 - val_accuracy: 0.7273 - val_loss: 1.4343
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9853 - loss: 0.0472 - val_accuracy: 0.7078 - val_loss: 1.3983
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9919 - loss: 0.0340 - val_accuracy: 0.7078 - val_loss: 1.5360
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9919 - loss: 0.0356 - val_accuracy: 0.7208 - val_loss: 1.5528
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9723 - loss: 0.0811 - val_accuracy: 0.7338 - val_loss: 1.5476
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9544 - loss: 0.1132 - val_accuracy: 0.7078 - val_loss: 1.5326
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9397 - loss: 0.1268 - val_accuracy: 0.7403 - val_loss: 1.3377
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9788 - loss: 0.0637 - val_accuracy: 0.7338 - val_loss: 1.4693
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9853 - loss: 0.0524 - val_accuracy: 0.7338 - val_loss: 1.4489
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9837 - loss: 0.0489 - val_accuracy: 0.7273 - val_loss: 1.5487
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9967 - loss: 0.0290 - val_accuracy: 0.7403 - val_loss: 1.5873
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9984 - loss: 0.0253 - val_accuracy: 0.7208 - val_loss: 1.5584
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9984 - loss: 0.0188 - val_accuracy: 0.7208 - val_loss: 1.6443
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.0166 - val_accuracy: 0.7078 - val_loss: 1.6958
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9967 - loss: 0.0381 - val_accuracy: 0.7208 - val_loss: 1.6796
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.0162 - val_accuracy: 0.7338 - val_loss: 1.7367
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9984 - loss: 0.0129 - val_accuracy: 0.7338 - val_loss: 1.7593
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0100 - val_accuracy: 0.7208 - val_loss: 1.8041
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0093 - val_accuracy: 0.7273 - val_loss: 1.8332
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0084 - val_accuracy: 0.7208 - val_loss: 1.8606
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0075 - val_accuracy: 0.7208 - val_loss: 1.8982
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0066 - val_accuracy: 0.7143 - val_loss: 1.9313
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0067 - val_accuracy: 0.7208 - val_loss: 1.9340
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.7143 - val_loss: 1.9956
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0062 - val_accuracy: 0.7208 - val_loss: 1.9945
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.7143 - val_loss: 2.0436
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.7273 - val_loss: 2.0553
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.7143 - val_loss: 2.0855
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0047 - val_accuracy: 0.7143 - val_loss: 2.1081
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.7273 - val_loss: 2.1192
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.7208 - val_loss: 2.1461
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0040 - val_accuracy: 0.7143 - val_loss: 2.1883
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0040 - val_accuracy: 0.7273 - val_loss: 2.1670
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0034 - val_accuracy: 0.7143 - val_loss: 2.2066
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.7143 - val_loss: 2.2195
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.7208 - val_loss: 2.2259
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.7273 - val_loss: 2.2829
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0046 - val_accuracy: 0.7143 - val_loss: 2.2714
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.7143 - val_loss: 2.2929
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.7208 - val_loss: 2.3076
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.7208 - val_loss: 2.3576
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.7143 - val_loss: 2.3425
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.7143 - val_loss: 2.3727
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.7208 - val_loss: 2.3806
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.7143 - val_loss: 2.4100
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.7143 - val_loss: 2.4092
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.7143 - val_loss: 2.4359
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.7143 - val_loss: 2.4380
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.7143 - val_loss: 2.4512
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.7143 - val_loss: 2.4703
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.7143 - val_loss: 2.4782
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.7143 - val_loss: 2.4909
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.7143 - val_loss: 2.4936
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.7143 - val_loss: 2.5271
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.7143 - val_loss: 2.5228
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.7143 - val_loss: 2.5425
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.7143 - val_loss: 2.5555
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.7143 - val_loss: 2.5716

In [50]:
def build_model(hp):
  model=Sequential()


  for i in range(hp.Int('num_layers', min_value=1, max_value=11)):
    if i == 0:
      model.add(Dense(
          units=hp.Int('unit' + str(i), min_value=8, max_value=128, step=9),
          activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),
          input_dim=8
      ))
      model.add(Dropout(
          hp.Choice('dropouts' + str(i), [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
      ))
    else:
      model.add(Dense(
          units=hp.Int('unit' + str(i), min_value=8, max_value=128, step=9),
          activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])
      ))
      model.add(Dropout(
          hp.Choice('dropouts' + str(i), [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
      ))

  model.add(Dense(1, activation='sigmoid'))
  model.compile(
      optimizer=hp.Choice('optimizer', values=['adam', 'rmsprop', 'nadam', 'sgd', 'adadelta']),
      loss='binary_crossentropy',
      metrics=['accuracy']
  )
  return model

In [51]:
tuner=kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=20,
    directory='test',
    project_name='all_types'
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [52]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 20 Complete [00h 00m 15s]
val_accuracy: 0.7077922224998474

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 03m 33s

In [53]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1,
 'unit0': 44,
 'activation0': 'relu',
 'dropouts0': 0.2,
 'optimizer': 'adam',
 'unit1': 98,
 'activation1': 'relu',
 'dropouts1': 0.9,
 'unit2': 8,
 'activation2': 'relu',
 'dropouts2': 0.3,
 'unit3': 125,
 'activation3': 'tanh',
 'dropouts3': 0.6,
 'unit4': 125,
 'activation4': 'tanh',
 'dropouts4': 0.5,
 'unit5': 98,
 'activation5': 'relu',
 'dropouts5': 0.4,
 'unit6': 62,
 'activation6': 'tanh',
 'dropouts6': 0.1,
 'unit7': 89,
 'activation7': 'tanh',
 'dropouts7': 0.8,
 'unit8': 8,
 'activation8': 'relu',
 'dropouts8': 0.7,
 'unit9': 8,
 'activation9': 'relu',
 'dropouts9': 0.3,
 'unit10': 26,
 'activation10': 'sigmoid',
 'dropouts10': 0.7}

In [55]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [56]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 44)             │           396 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 44)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            45 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 441 (1.72 KB)

 Trainable params: 441 (1.72 KB)

 Non-trainable params: 0 (0.00 B)

In [57]:
model.fit(X_train, y_train, epochs=200, validation_data=(X_test, y_test))

Epoch 1/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 7s 163ms/step - accuracy: 0.7638 - loss: 0.5254 - val_accuracy: 0.7857 - val_loss: 0.4925
Epoch 2/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7557 - loss: 0.5076 - val_accuracy: 0.7857 - val_loss: 0.4798
Epoch 3/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7655 - loss: 0.4986 - val_accuracy: 0.7727 - val_loss: 0.4724
Epoch 4/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.7915 - loss: 0.4833 - val_accuracy: 0.7662 - val_loss: 0.4670
Epoch 5/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7769 - loss: 0.4809 - val_accuracy: 0.7662 - val_loss: 0.4651
Epoch 6/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4710 - val_accuracy: 0.7597 - val_loss: 0.4628
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4815 - val_accuracy: 0.7532 - val_loss: 0.4617
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7785 - loss: 0.4607 - val_accuracy: 0.7727 - val_loss: 0.4607
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7671 - loss: 0.4668 - val_accuracy: 0.7727 - val_loss: 0.4598
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7655 - loss: 0.4680 - val_accuracy: 0.7662 - val_loss: 0.4607
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7785 - loss: 0.4605 - val_accuracy: 0.7662 - val_loss: 0.4603
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7769 - loss: 0.4602 - val_accuracy: 0.7662 - val_loss: 0.4590
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7785 - loss: 0.4678 - val_accuracy: 0.7662 - val_loss: 0.4587
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7752 - loss: 0.4501 - val_accuracy: 0.7662 - val_loss: 0.4619
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4522 - val_accuracy: 0.7792 - val_loss: 0.4611
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4596 - val_accuracy: 0.7792 - val_loss: 0.4582
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4561 - val_accuracy: 0.7792 - val_loss: 0.4605
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4556 - val_accuracy: 0.7792 - val_loss: 0.4592
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4528 - val_accuracy: 0.7727 - val_loss: 0.4576
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4521 - val_accuracy: 0.7727 - val_loss: 0.4583
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7655 - loss: 0.4593 - val_accuracy: 0.7727 - val_loss: 0.4610
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4509 - val_accuracy: 0.7792 - val_loss: 0.4617
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7752 - loss: 0.4512 - val_accuracy: 0.7727 - val_loss: 0.4625
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7866 - loss: 0.4499 - val_accuracy: 0.7792 - val_loss: 0.4617
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7883 - loss: 0.4494 - val_accuracy: 0.7792 - val_loss: 0.4616
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7818 - loss: 0.4521 - val_accuracy: 0.7792 - val_loss: 0.4618
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7720 - loss: 0.4631 - val_accuracy: 0.7792 - val_loss: 0.4626
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7899 - loss: 0.4361 - val_accuracy: 0.7792 - val_loss: 0.4625
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7785 - loss: 0.4499 - val_accuracy: 0.7792 - val_loss: 0.4616
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7785 - loss: 0.4377 - val_accuracy: 0.7792 - val_loss: 0.4609
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4415 - val_accuracy: 0.7792 - val_loss: 0.4617
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4437 - val_accuracy: 0.7792 - val_loss: 0.4605
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7785 - loss: 0.4468 - val_accuracy: 0.7857 - val_loss: 0.4601
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4442 - val_accuracy: 0.7792 - val_loss: 0.4620
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4536 - val_accuracy: 0.7792 - val_loss: 0.4614
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7818 - loss: 0.4379 - val_accuracy: 0.7792 - val_loss: 0.4609
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4461 - val_accuracy: 0.7792 - val_loss: 0.4616
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4488 - val_accuracy: 0.7857 - val_loss: 0.4648
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4420 - val_accuracy: 0.7922 - val_loss: 0.4650
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4351 - val_accuracy: 0.7857 - val_loss: 0.4647
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4474 - val_accuracy: 0.7922 - val_loss: 0.4652
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4496 - val_accuracy: 0.7987 - val_loss: 0.4622
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4403 - val_accuracy: 0.7987 - val_loss: 0.4634
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4397 - val_accuracy: 0.7987 - val_loss: 0.4622
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4386 - val_accuracy: 0.7987 - val_loss: 0.4625
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7801 - loss: 0.4398 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4459 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4324 - val_accuracy: 0.7987 - val_loss: 0.4625
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7915 - loss: 0.4381 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4432 - val_accuracy: 0.7987 - val_loss: 0.4637
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4330 - val_accuracy: 0.7987 - val_loss: 0.4637
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4373 - val_accuracy: 0.7987 - val_loss: 0.4636
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4369 - val_accuracy: 0.7987 - val_loss: 0.4608
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4335 - val_accuracy: 0.7987 - val_loss: 0.4599
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4385 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4394 - val_accuracy: 0.7987 - val_loss: 0.4628
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8013 - loss: 0.4260 - val_accuracy: 0.7987 - val_loss: 0.4648
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4434 - val_accuracy: 0.7987 - val_loss: 0.4644
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4406 - val_accuracy: 0.8052 - val_loss: 0.4639
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4389 - val_accuracy: 0.8052 - val_loss: 0.4658
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7752 - loss: 0.4335 - val_accuracy: 0.8052 - val_loss: 0.4658
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4370 - val_accuracy: 0.7987 - val_loss: 0.4642
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4259 - val_accuracy: 0.7987 - val_loss: 0.4644
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4304 - val_accuracy: 0.8052 - val_loss: 0.4640
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7818 - loss: 0.4381 - val_accuracy: 0.8052 - val_loss: 0.4626
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7818 - loss: 0.4346 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4321 - val_accuracy: 0.8052 - val_loss: 0.4624
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7801 - loss: 0.4396 - val_accuracy: 0.8052 - val_loss: 0.4636
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7932 - loss: 0.4339 - val_accuracy: 0.8052 - val_loss: 0.4675
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7834 - loss: 0.4210 - val_accuracy: 0.7987 - val_loss: 0.4655
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7769 - loss: 0.4351 - val_accuracy: 0.7987 - val_loss: 0.4668
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7932 - loss: 0.4328 - val_accuracy: 0.7987 - val_loss: 0.4642
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7866 - loss: 0.4387 - val_accuracy: 0.7987 - val_loss: 0.4627
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7883 - loss: 0.4247 - val_accuracy: 0.7987 - val_loss: 0.4650
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4304 - val_accuracy: 0.7987 - val_loss: 0.4652
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4318 - val_accuracy: 0.7987 - val_loss: 0.4649
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8029 - loss: 0.4218 - val_accuracy: 0.7987 - val_loss: 0.4638
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4248 - val_accuracy: 0.7987 - val_loss: 0.4637
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4241 - val_accuracy: 0.7987 - val_loss: 0.4646
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4294 - val_accuracy: 0.7922 - val_loss: 0.4668
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4275 - val_accuracy: 0.7922 - val_loss: 0.4661
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4230 - val_accuracy: 0.7922 - val_loss: 0.4658
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4255 - val_accuracy: 0.8052 - val_loss: 0.4637
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4353 - val_accuracy: 0.8052 - val_loss: 0.4626
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4299 - val_accuracy: 0.8052 - val_loss: 0.4641
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4292 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4228 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7932 - loss: 0.4291 - val_accuracy: 0.8052 - val_loss: 0.4629
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4310 - val_accuracy: 0.8052 - val_loss: 0.4659
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4210 - val_accuracy: 0.8052 - val_loss: 0.4643
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8046 - loss: 0.4264 - val_accuracy: 0.8052 - val_loss: 0.4636
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7964 - loss: 0.4250 - val_accuracy: 0.7987 - val_loss: 0.4640
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7866 - loss: 0.4232 - val_accuracy: 0.8052 - val_loss: 0.4636
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7915 - loss: 0.4202 - val_accuracy: 0.8052 - val_loss: 0.4636
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4251 - val_accuracy: 0.8052 - val_loss: 0.4643
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4285 - val_accuracy: 0.8052 - val_loss: 0.4639
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4324 - val_accuracy: 0.8052 - val_loss: 0.4653
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4207 - val_accuracy: 0.8052 - val_loss: 0.4654
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4305 - val_accuracy: 0.8052 - val_loss: 0.4645
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4242 - val_accuracy: 0.8052 - val_loss: 0.4660
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4300 - val_accuracy: 0.8052 - val_loss: 0.4668
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4264 - val_accuracy: 0.8052 - val_loss: 0.4645
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4310 - val_accuracy: 0.8052 - val_loss: 0.4649
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7948 - loss: 0.4240 - val_accuracy: 0.8052 - val_loss: 0.4673
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4216 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7997 - loss: 0.4204 - val_accuracy: 0.8052 - val_loss: 0.4665
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4285 - val_accuracy: 0.8052 - val_loss: 0.4656
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7964 - loss: 0.4263 - val_accuracy: 0.8052 - val_loss: 0.4639
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7997 - loss: 0.4231 - val_accuracy: 0.8052 - val_loss: 0.4661
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7932 - loss: 0.4223 - val_accuracy: 0.8052 - val_loss: 0.4664
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7948 - loss: 0.4202 - val_accuracy: 0.8052 - val_loss: 0.4676
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7980 - loss: 0.4238 - val_accuracy: 0.8052 - val_loss: 0.4645
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7997 - loss: 0.4262 - val_accuracy: 0.8052 - val_loss: 0.4641
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7866 - loss: 0.4292 - val_accuracy: 0.8052 - val_loss: 0.4639
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4218 - val_accuracy: 0.8052 - val_loss: 0.4657
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4100 - val_accuracy: 0.8052 - val_loss: 0.4680
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7997 - loss: 0.4216 - val_accuracy: 0.8052 - val_loss: 0.4658
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8208 - loss: 0.4081 - val_accuracy: 0.8052 - val_loss: 0.4678
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4167 - val_accuracy: 0.7987 - val_loss: 0.4689
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4115 - val_accuracy: 0.7987 - val_loss: 0.4680
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8078 - loss: 0.4234 - val_accuracy: 0.8052 - val_loss: 0.4659
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8013 - loss: 0.4169 - val_accuracy: 0.8052 - val_loss: 0.4661
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4205 - val_accuracy: 0.8052 - val_loss: 0.4676
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4324 - val_accuracy: 0.8052 - val_loss: 0.4666
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8078 - loss: 0.4128 - val_accuracy: 0.7987 - val_loss: 0.4678
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4265 - val_accuracy: 0.8052 - val_loss: 0.4681
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4205 - val_accuracy: 0.8052 - val_loss: 0.4664
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4202 - val_accuracy: 0.8052 - val_loss: 0.4643
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7997 - loss: 0.4186 - val_accuracy: 0.8052 - val_loss: 0.4654
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8062 - loss: 0.4163 - val_accuracy: 0.7987 - val_loss: 0.4660
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4155 - val_accuracy: 0.8052 - val_loss: 0.4647
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4200 - val_accuracy: 0.8052 - val_loss: 0.4641
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4176 - val_accuracy: 0.8052 - val_loss: 0.4653
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8111 - loss: 0.4054 - val_accuracy: 0.8052 - val_loss: 0.4656
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4178 - val_accuracy: 0.8052 - val_loss: 0.4672
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4179 - val_accuracy: 0.8052 - val_loss: 0.4670
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4255 - val_accuracy: 0.8052 - val_loss: 0.4691
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8013 - loss: 0.4182 - val_accuracy: 0.8052 - val_loss: 0.4696
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4122 - val_accuracy: 0.8052 - val_loss: 0.4691
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4185 - val_accuracy: 0.8052 - val_loss: 0.4684
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7997 - loss: 0.4123 - val_accuracy: 0.8052 - val_loss: 0.4666
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4165 - val_accuracy: 0.8052 - val_loss: 0.4655
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4235 - val_accuracy: 0.8052 - val_loss: 0.4696
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4304 - val_accuracy: 0.7987 - val_loss: 0.4680
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8062 - loss: 0.4173 - val_accuracy: 0.7987 - val_loss: 0.4688
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7915 - loss: 0.4210 - val_accuracy: 0.8052 - val_loss: 0.4667
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4116 - val_accuracy: 0.7987 - val_loss: 0.4667
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8111 - loss: 0.4164 - val_accuracy: 0.7987 - val_loss: 0.4672
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.4059 - val_accuracy: 0.8052 - val_loss: 0.4671
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4318 - val_accuracy: 0.7987 - val_loss: 0.4680
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4258 - val_accuracy: 0.8117 - val_loss: 0.4649
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4125 - val_accuracy: 0.8052 - val_loss: 0.4655
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4195 - val_accuracy: 0.8052 - val_loss: 0.4661
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4206 - val_accuracy: 0.8052 - val_loss: 0.4658
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4123 - val_accuracy: 0.8052 - val_loss: 0.4667